spring:
  application:
    name: namaskar-server
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    hikari:
      max-lifetime: ${DB_HIKARI_MAX_LIFETIME}
      idle-timeout: ${DB_IDLE_TIMEOUT}
      connection-timeout: ${DB_CONNECTION_TIMEOUT}
  jpa:
    show-sql: ${DB_SHOW_SQL}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ${DB_FORMAT_SQL}
        connection:
          timezone: ${DB_CONNECTION_TIMEZONE}
    database: ${DATABASE_NAME}
    database-platform: ${DATABASE_PLATFORM}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
application:
  security:
    jwt:
      access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
      refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
      secret-key: ${SERVER_SECRET}
    access-origins:
      frontend: ${FRONTEND_URL}
  mail:
    from: ${MAIL_FROM}
    reply-to: ${MAIL_REPLY_TO}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
