spring:
  application:
    name: namaskar-server
  datasource:
    url: jdbc:postgresql://localhost:5432/namaskar
    username: postgres
    password: postgres-password
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 60000
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        connection:
          timezone: Asia/Kolkata
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
application:
  security:
    jwt:
      access-token-expiration: 900000 # Access token expires in 15 minutes
      refresh-token-expiration: 604800000 # Refresh token expires in 7 days
      secret-key: ${SERVER_SECRET}
    access-origins:
      frontend: ${FRONTEND_URL}
  mail:
    from: ${MAIL_FROM}
    reply-to: ${MAIL_REPLY_TO}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
