spring:
  application:
    name: namaskar-server
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
  devtools:
    restart:
      enabled: false
# logging:
#   level:
#     dev:
#       aniketkadam: trace